Added configure check for unaligned memcpy support and cleaned up macros

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -4864,7 +4864,7 @@ if (eval "$ac_cpp conftest.$ac_ext") 2>&5 |
 else
   ac_cv_header_stdc=no
 fi
-rm -f conftest*
+rm -f -r conftest*
 
 fi
 
@@ -4885,7 +4885,7 @@ if (eval "$ac_cpp conftest.$ac_ext") 2>&5 |
 else
   ac_cv_header_stdc=no
 fi
-rm -f conftest*
+rm -f -r conftest*
 
 fi
 
@@ -19884,7 +19884,7 @@ if (eval "$ac_cpp conftest.$ac_ext") 2>&5 |
 else
   ac_cv_header_stdc=no
 fi
-rm -f conftest*
+rm -f -r conftest*
 
 fi
 
@@ -19905,7 +19905,7 @@ if (eval "$ac_cpp conftest.$ac_ext") 2>&5 |
 else
   ac_cv_header_stdc=no
 fi
-rm -f conftest*
+rm -f -r conftest*
 
 fi
 
@@ -21508,6 +21508,110 @@ _ACEOF
   LIBS="-lgetopt $LIBS"
 
 fi
+
+
+# Check for memcpy unaligned copy support
+{ echo "$as_me:$LINENO: checking whether memcpy works with unaligned data" >&5
+echo $ECHO_N "checking whether memcpy works with unaligned data... $ECHO_C" >&6; }
+if test "$cross_compiling" = yes; then
+
+{ echo "$as_me:$LINENO: result: can not test" >&5
+echo "${ECHO_T}can not test" >&6; }
+
+else
+  cat >conftest.$ac_ext <<_ACEOF
+
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <stdio.h>
+#include <stdlib.h>
+#include <stdint.h>
+#include <string.h>
+#define READ_UNALIGNED(val, addr, size)  memcpy(&(val), (addr), size)
+typedef struct struct_type_t {
+  uint32_t	numx;
+  uint32_t	numy;
+  uint8_t   data[1];
+} struct_type_t;
+int
+main ()
+{
+uint8_t	*init = "WithThisDataICanFindManyBugs\0\0\0\0";
+uint8_t *data = malloc(sizeof(uint8_t)*32);
+struct_type_t *good_data = (struct_type_t *)(data+0);
+struct_type_t *poor_data = (struct_type_t *)(data+1);
+uint32_t numx = 0;
+uint32_t numy = 0;
+uint8_t  ebytes[] = {0xFF,0x11};
+uint16_t echeck = ebytes[0]|ebytes[1]<< 8;
+uint16_t endian = *((uint16_t*)(&ebytes[0]));
+uint8_t  little = (endian == echeck);
+memcpy(&data[0],&init[0],32);
+if(memcmp(&data[0],&init[0],32) != 0) return 1;
+READ_UNALIGNED(numx, &(poor_data->numx),sizeof( uint32_t));
+if( (little && numx != 0x54687469) || (!little && numx != 0x69746854) ) return 1;
+READ_UNALIGNED(numy, &(poor_data->numy),sizeof( uint32_t));
+if( (little && numy != 0x44736968) || (!little && numy != 0x68697344) ) return 1;
+READ_UNALIGNED(numx, &(good_data->numx),sizeof( uint32_t));
+if( (little && numx != 0x68746957) || (!little && numx != 0x57697468) ) return 1;
+READ_UNALIGNED(numy, &(good_data->numy),sizeof( uint32_t));
+if( (little && numy != 0x73696854) || (!little && numy != 0x54686973) ) return 1;
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest$ac_exeext
+if { (ac_try="$ac_link"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_link") 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && { ac_try='./conftest$ac_exeext'
+  { (case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_try") 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_UNALIGNED_MEMCPY 1
+_ACEOF
+
+{ echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6; }
+
+else
+  echo "$as_me: program exited with status $ac_status" >&5
+echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+( exit $ac_status )
+
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_UNALIGNED_MEMCPY 0
+_ACEOF
+
+{ echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+
+fi
+rm -f core *.core core.conftest.* gmon.out bb.out conftest$ac_exeext conftest.$ac_objext conftest.$ac_ext
+fi
+
 
 
 # Check for libpng
@@ -23728,7 +23832,7 @@ do
     cat >>$CONFIG_STATUS <<_ACEOF
     # First, check the format of the line:
     cat >"\$tmp/defines.sed" <<\\CEOF
-/^[	 ]*#[	 ]*undef[	 ][	 ]*$ac_word_re[	 ]*\$/b def
+/^[	 ]*#[	 ]*undef[	 ][	 ]*$ac_word_re[	 ]*/b def
 /^[	 ]*#[	 ]*define[	 ][	 ]*$ac_word_re[(	 ]/b def
 b
 :def
